name: Android Unit Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          architecture: x64
          distribution: 'adopt'
          check-latest: false
          overwrite-settings: true

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.java') }}-${{ hashFiles('**/*.kts') }}-${{ hashFiles('**/build.gradle*') }}-${{ hashFiles('**/settings.gradle*') }}-${{ hashFiles('**/*.properties') }}

      - name: Debug Information
        run: |
          ls -R ${{ github.workspace }}

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assemble
        shell: bash

      - name: Get Commit Hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - name: AppSweep Mobile Application Security Testing
        uses: Guardsquare/appsweep-action@v1.5
        with:
          appsweep_api_key: gs_appsweep_0BzKyw3_wROiJgUkw3TpUzkVoUaCyMFihKwUcPPE
          input_file: app/build/outputs/apk/debug/app-debug.apk
          commit_hash: ${{ steps.commit_hash.outputs.hash }}

      - name: Run Unit Tests
        run: ./gradlew test
        shell: bash
