name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.1.1

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '1.8'
        architecture: 'x64'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3
      with:
         name: app
         path: app/build/outputs/apk/debug/app-debug.apk
